apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: pycon-hpa
  namespace: openfaas-fn
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pycon
  minReplicas: 5
  maxReplicas: 20
  metrics:
    - type: Pods
      pods:
        metric:
          name: http_requests_per_second
        target:
          type: AverageValue
          averageValue: 0.5
