apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: pycon-hpa
  namespace: openfaas-fn
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pycon
  minReplicas: 5
  maxReplicas: 20
  metrics:
    - type: External
      external:
        metric:
          name: gateway_function_invocation_per_second
          selector: "function_name="pycon.openfaas-fn""
        target:
          type: AverageValue
          averageValue: 0.5
