apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: primality-hpa
  namespace: openfaas-fn
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: primality
  minReplicas: 1
  maxReplicas: 50
  metrics:
  - type: External
    external:
      metric:
        name: gateway_function_invocation_per_second
      target:
        type: AverageValue
        averageValue: 0.1
